sudo: required
services:
  - docker

before-install:
  - docker build -t ivokaramfilov1/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true ivokaramfilov1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-227546792146"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"